version: '2'
services:
  generate:
    build: .
    volumes:
    - .:/app
    command: python3 main.py
  server:
    build: .
    ports:
    - "8000:5000"
    volumes:
    - .:/app
    command: python web.py
  dev:
    build: .
    ports:
    - "8001:5000"
    volumes:
    - .:/app
    environment:
    - FLASK_DEBUG=1
    command: python web.py
  tests:
    build: tests
    volumes:
    - "./:/app"
    command: pytest tests
  http:
    image: nginx
    volumes:
    - "./http_conf:/etc/nginx/conf.d/"
    - "./data:/data"
#    ports:
#    - "80:80"